export default function Legal() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-foreground/8 px-4 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <span className="font-serif-display text-lg font-bold tracking-tight">
            The Policy Lab
          </span>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-10 sm:py-14">
        <div className="border-t-2 border-primary pt-3 mb-4 flex items-center gap-3">
          <span className="font-mono text-[10px] font-bold tracking-[0.2em] uppercase text-primary">
            Legal & Disclaimers
          </span>
          <div className="flex-1 h-px bg-gradient-to-r from-primary/25 to-transparent" />
        </div>

        <h1 className="font-serif-display text-3xl sm:text-4xl font-black mb-3 leading-tight">
          The fine print.
        </h1>
        <p className="text-sm text-muted-foreground mb-10 leading-relaxed">
          Last updated: July 22, 2026
        </p>

        <section className="space-y-3 mb-10">
          <h2 className="font-mono text-[11px] font-bold tracking-[0.18em] uppercase text-primary">
            Not Legal Advice
          </h2>
          <div className="rounded-2xl p-5 border-l-4 border-l-destructive bg-destructive/5">
            <p className="text-sm font-bold text-destructive mb-2">
              The Policy Lab does not provide legal advice.
            </p>
            <p className="text-sm leading-relaxed text-foreground/85">
              All output produced by this tool is generated by artificial
              intelligence and is provided <span className="font-bold">for informational purposes only</span>.
              Nothing here constitutes legal, regulatory, accounting, tax, or
              professional advice, and using this tool does not create any kind
              of attorney–client, advisor–client, or fiduciary relationship.
            </p>
            <p className="text-sm leading-relaxed text-foreground/85 mt-2">
              Always have a qualified attorney or licensed compliance
              professional review any policy, gap analysis, or recommendation
              before relying on it, publishing it, or submitting it to a
              regulator, board, or counterparty.
            </p>
          </div>
        </section>

        <section className="space-y-3 mb-10">
          <h2 className="font-mono text-[11px] font-bold tracking-[0.18em] uppercase text-primary">
            AI Output May Be Wrong
          </h2>
          <p className="text-sm leading-relaxed text-foreground/85">
            This tool uses large language models to draft and analyze policies.
            AI systems can and do produce inaccurate, incomplete, outdated, or
            entirely fabricated information — including incorrect citations to
            laws and regulations that do not say what the tool claims they say.
          </p>
          <p className="text-sm leading-relaxed text-foreground/85">
            You are solely responsible for verifying every fact, citation, and
            recommendation before acting on it. Final judgment and
            responsibility for any policy decision remain entirely with you.
          </p>
        </section>

        <section className="space-y-3 mb-10">
          <h2 className="font-mono text-[11px] font-bold tracking-[0.18em] uppercase text-primary">
            How Your Data Is Handled
          </h2>
          <p className="text-sm leading-relaxed text-foreground/85">
            The Policy Lab is stateless. We do not require an account, and we
            do not store the policies, descriptions, or files you submit on our
            servers after your request is processed.
          </p>
          <p className="text-sm leading-relaxed text-foreground/85">
            To generate output, the text you submit is sent to a third-party
            AI provider for processing, and to search regulatory sources
            online. Those providers have their own privacy policies and
            data-handling practices, which apply to your content while it is
            in their systems.
          </p>
          <p className="text-sm leading-relaxed text-foreground/85">
            <span className="font-bold">Do not paste anything you would not be comfortable sending to a third-party AI provider.</span>{" "}
            That includes confidential client information, protected health
            information (PHI), trade secrets, attorney work product, or any
            other material subject to a confidentiality obligation.
          </p>
        </section>

        <section className="space-y-3 mb-10">
          <h2 className="font-mono text-[11px] font-bold tracking-[0.18em] uppercase text-primary">
            No Warranty
          </h2>
          <p className="text-sm leading-relaxed text-foreground/85">
            This tool is provided <span className="font-mono text-xs">"AS IS"</span> and{" "}
            <span className="font-mono text-xs">"AS AVAILABLE"</span>, without
            warranty of any kind, express or implied, including but not limited
            to warranties of merchantability, fitness for a particular purpose,
            accuracy, or non-infringement. Use of this tool is entirely at your
            own risk.
          </p>
        </section>

        <section className="space-y-3 mb-10">
          <h2 className="font-mono text-[11px] font-bold tracking-[0.18em] uppercase text-primary">
            Limitation of Liability
          </h2>
          <p className="text-sm leading-relaxed text-foreground/85">
            To the fullest extent permitted by law, in no event shall The
            Policy Lab, its operator, or any contributor be liable for any
            direct, indirect, incidental, special, consequential, exemplary, or
            punitive damages — including but not limited to regulatory
            penalties, fines, lost profits, lost data, or business interruption
            — arising out of or in connection with your use of, or inability to
            use, this tool, even if advised of the possibility of such damages.
          </p>
        </section>

        <section className="space-y-3 mb-10">
          <h2 className="font-mono text-[11px] font-bold tracking-[0.18em] uppercase text-primary">
            Acceptable Use
          </h2>
          <p className="text-sm leading-relaxed text-foreground/85">
            You agree not to use this tool to (a) violate any law or regulation,
            (b) abuse, overload, or attempt to disrupt the service, (c)
            misrepresent AI-generated output as the work of a licensed
            professional, or (d) submit content you do not have the right to
            share with third-party AI providers.
          </p>
        </section>

        <section className="space-y-3 mb-10">
          <h2 className="font-mono text-[11px] font-bold tracking-[0.18em] uppercase text-primary">
            Changes to These Terms
          </h2>
          <p className="text-sm leading-relaxed text-foreground/85">
            These terms may be updated at any time without notice. Continued
            use of the tool after a change constitutes acceptance of the
            updated terms.
          </p>
        </section>

        <section className="space-y-3 mb-10">
          <h2 className="font-mono text-[11px] font-bold tracking-[0.18em] uppercase text-primary">
            Contact
          </h2>
          <p className="text-sm leading-relaxed text-foreground/85">
            Questions, concerns, or notices regarding this tool can be directed
            to its operator, Andrew Weingarten.
          </p>
        </section>

      </main>

      <footer className="border-t border-foreground/8 px-4 py-8 text-center">
        <p className="text-[10px] text-muted-foreground/35 font-mono tracking-wider">
          Built by Andrew Weingarten
        </p>
      </footer>
    </div>
  );
}
